MARKET_TRADING_DATE = "06/11/2020"
BUYSELL_PLOT_HEIGHT = 240
PS_PLOT_HEIGHT = 200
DIV_TEXT_WIDTH = 400
PLOT_WIDTH = 1200
OHLC_PLOT_HEIGHT = 530
VOLUME_PLOT_HEIGHT = 130
LIQUIDITY_ALPHA = 0.3


HOSE_ENDPOINT_PORT = 5000
PS_ENDPOINT_PORT = 5001
SUU_ENDPOINT_PORT = 5010
SUU_URL = f"http://localhost:{SUU_ENDPOINT_PORT}/suu-data-out"
HOSE_URL = f'http://localhost:{HOSE_ENDPOINT_PORT}/api/hose-indicators-outbound'
PS_URL = f'http://localhost:{PS_ENDPOINT_PORT}/ps-pressure-out'
